// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB__0uRNimlvuPnDUmapjCKecUGrl5xEK0',
    appId: '1:629680213555:android:ce1b944a2faa4d46989d46',
    messagingSenderId: '629680213555',
    projectId: 'dev-konverge',
    storageBucket: 'dev-konverge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHvf8C7NqE4KGqTn7TE63MHWh7MBf-EUE',
    appId: '1:629680213555:ios:0e3f1b82f04312f5989d46',
    messagingSenderId: '629680213555',
    projectId: 'dev-konverge',
    storageBucket: 'dev-konverge.appspot.com',
    androidClientId: '629680213555-c27ecgvda3rtmtufp5ro8drptkf42amb.apps.googleusercontent.com',
    iosClientId: '629680213555-qfg1mu3f7me28ekcujpt43fm8m2nl4ni.apps.googleusercontent.com',
    iosBundleId: 'com.app.konverge',
  );
}
